<?php
    /** @var Webgriffe_TaxIdPro_Block_Fields $this */

    $editBlock = $this->getParentBlock();
?>
<!-- TaxIdPro - Begin -->
<li class="fields">
    <div class="field">
        <label for="<?php echo $this->getIsBusinessAddressId() ?>" class="required"><em>*</em><?php echo $editBlock->__('Is it a Business Address') ?></label>
        <div class="input-box">
            <select name="<?php echo $this->getIsBusinessAddressName() ?>"  title="<?php echo $editBlock->__('Is it a Business Address') ?>" class="required-entry" id="<?php echo $this->getIsBusinessAddressId() ?>">
                <option value="0" <?php echo $editBlock->getAddress()->getIsBusinessAddress() ? '' : 'selected="selected"' ?>><?php print $editBlock->__('No') ?></option>
                <option value="1" <?php echo $editBlock->getAddress()->getIsBusinessAddress() ? 'selected="selected"' : '' ?>><?php print $editBlock->__('Yes') ?></option>
            </select>
        </div>
    </div>
    <div class="field">
        <label for="<?php echo $this->getTaxCodeId() ?>" class="required"><em id="<?php echo $this->getTaxCodeEmId() ?>">*</em><?php echo $editBlock->__('Tax Code') ?></label>
        <div class="input-box">
            <input type="text" name="<?php echo $this->getTaxCodeName() ?>" value="<?php echo $editBlock->escapeHtml($editBlock->getAddress()->getTaxCode()) ?>" title="<?php echo $editBlock->__('Tax Code') ?>" class="input-text required-entry validate-tax_code" id="<?php echo $this->getTaxCodeId() ?>" style="text-transform:uppercase;" />
        </div>
    </div>
</li>

<li class="fields show-in-business-only" <?php echo $editBlock->getAddress()->getIsBusinessAddress() ? '' : 'style="display:none;"' ?>>
    <div class="field">
        <label for="<?php echo $this->getCompanyId() ?>" class="required"><em>*</em><?php echo $editBlock->__('Company') ?></label>
        <div class="input-box">
            <input type="text" name="<?php echo $this->getCompanyName() ?>" id="<?php echo $this->getCompanyId() ?>" title="<?php echo $editBlock->__('Company') ?>" value="<?php echo $editBlock->escapeHtml($editBlock->getAddress()->getCompany()) ?>" class="input-text required-entry" />
        </div>
    </div>
    <div class="field">
        <label for="<?php echo $this->getVatNumberId() ?>" class="required"><em id="<?php echo $this->getVatNumberEmId() ?>">*</em><?php echo $editBlock->__('VAT Number') ?></label>
        <div class="input-box">
            <input type="text" name="<?php echo $this->getVatNumberName() ?>" value="<?php echo $editBlock->escapeHtml($editBlock->getAddress()->getVatNumber()) ?>" title="<?php echo $editBlock->__('VAT Number') ?>" class="input-text required-entry validate-vat_number" id="<?php echo $this->getVatNumberId() ?>" />
        </div>
    </div>
</li>

<?php echo $this->getChildHtml('webgriffe_taxidpro_javascripts') ?>

<!-- TaxIdPro - End -->
