<?php
    /** @var Webgriffe_TaxIdPro_Block_Fields $editBlock */

    $editBlock = $this->getParentBlock();
    $blockAlias = preg_replace('/[^a-zA-Z]/', '', $editBlock->getParentBlock()->getBlockAlias());
?>

<script type="text/javascript">
    //<![CDATA[
    function <?php echo $blockAlias ?>CountryIsRequired(element) {
        var taxCodeIsRequiredForItaly = <?php echo json_encode($this->helper('webgriffe_taxidpro')->isTaxCodeRequired()) ?>;
        if(taxCodeIsRequiredForItaly && element.getValue() == 'IT') {
            $('<?php echo $editBlock->getTaxCodeEmId() ?>').innerHTML = '*';
            $('<?php echo $editBlock->getTaxCodeId() ?>').addClassName('required-entry');
        }
        else {
            $('<?php echo $editBlock->getTaxCodeEmId() ?>').innerHTML = '';
            if ($('advice-required-entry-<?php echo $editBlock->getTaxCodeId() ?>')) {
                $('advice-required-entry-<?php echo $editBlock->getTaxCodeId() ?>').hide();
            }
            $('<?php echo $editBlock->getTaxCodeId() ?>').removeClassName('required-entry');
        }

        var vatNumberIsRequiredForItaly = <?php echo json_encode($this->helper('webgriffe_taxidpro')->isVatNumberRequired()) ?>;
        if(vatNumberIsRequiredForItaly && element.getValue() == 'IT') {
            $('<?php echo $editBlock->getVatNumberEmId() ?>').innerHTML = '*';
            $('<?php echo $editBlock->getVatNumberId() ?>').addClassName('required-entry');
        }
        else {
            $('<?php echo $editBlock->getVatNumberEmId() ?>').innerHTML = '';
            if ($('advice-required-entry-<?php echo $editBlock->getVatNumberId() ?>')) {
                $('advice-required-entry-<?php echo $editBlock->getVatNumberId() ?>').hide();
            }
            $('<?php echo $editBlock->getVatNumberId() ?>').removeClassName('required-entry');
        }
    }

    function ControllaCF(cf)
    {
        var validi, i, s, set1, set2, setpari, setdisp;
        if( cf == '' )  {
            return true;
        }
        cf = cf.toUpperCase();
        if( cf.length != 16 ) {
            return false;
        }
        validi = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        for( i = 0; i < 16; i++ ){
            if( validi.indexOf( cf.charAt(i) ) == -1 ) {
                return false;
            }
        }
        set1 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        set2 = "ABCDEFGHIJABCDEFGHIJKLMNOPQRSTUVWXYZ";
        setpari = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        setdisp = "BAKPLCQDREVOSFTGUHMINJWZYX";
        s = 0;
        for( i = 1; i <= 13; i += 2 ) {
            s += setpari.indexOf( set2.charAt( set1.indexOf( cf.charAt(i) )));
        }
        for( i = 0; i <= 14; i += 2 ) {
            s += setdisp.indexOf( set2.charAt( set1.indexOf( cf.charAt(i) )));
        }
        return ( s%26 == cf.charCodeAt(15)-'A'.charCodeAt(0) );
    }

    function ControllaPIVA(pi)
    {
        if( pi == '' )  {
            return true;
        }
        if( pi.length != 11 ) {
            return false;
        }
        validi = "0123456789";
        for( i = 0; i < 11; i++ ){
            if( validi.indexOf( pi.charAt(i) ) == -1 ) {
                return false;
            }
        }
        s = 0;
        for( i = 0; i <= 9; i += 2 ) {
            s += pi.charCodeAt(i) - '0'.charCodeAt(0);
        }
        for( i = 1; i <= 9; i += 2 ) {
            c = 2*( pi.charCodeAt(i) - '0'.charCodeAt(0) );
            if( c > 9 ) {
                c = c - 9;
            }
            s += c;
        }
        return ( ( 10 - s%10 )%10 == pi.charCodeAt(10) - '0'.charCodeAt(0) );
    }

    function toggleBusinessFields(isBusinessAddressElement) {
        if (parseInt(isBusinessAddressElement.getValue())) { // If is a business address...
            $$('.show-in-business-only').invoke('show');
        }
        else {
            $('<?php echo $editBlock->getVatNumberId() ?>').setValue('');
            $('<?php echo $editBlock->getCompanyId() ?>').setValue('');
            $$('.show-in-business-only').invoke('hide');
        }
    }

    Event.observe(window, 'load', function() {
        $('<?php echo $editBlock->getIsBusinessAddressId() ?>').observe('change', function(event) {
            toggleBusinessFields(this);
        });

        $('<?php echo $editBlock->getTaxCodeId() ?>').observe('blur', function(event) {
            this.setValue(this.getValue().toUpperCase());
        });
        $('<?php echo $editBlock->getVatNumberId() ?>').observe('blur', function(event) {
            this.setValue(this.getValue().toUpperCase());
        });

        Validation.addAllThese([
            ['validate-tax_code', '<?php echo $editBlock->__("Please, enter a valid Tax Code.") ?>', function (v, elm) {
                elm.value = elm.value.toUpperCase();
                return $('<?php echo $editBlock->getCountryId() ?>').value != 'IT' || ControllaCF(elm.value) || ControllaPIVA(elm.value);
            }],
            ['validate-vat_number', '<?php echo $editBlock->__("Please, enter a valid VAT Number.") ?>', function (v, elm) {
                elm.value = elm.value.toUpperCase();
                return $('<?php echo $editBlock->getCountryId() ?>').value != 'IT' || ControllaPIVA(elm.value);
            }]
        ]);

        <?php echo $blockAlias ?>CountryIsRequired($('<?php echo $editBlock->getCountryId() ?>'));

        $('<?php echo $editBlock->getCountryId() ?>').observe('change', function(event) {
            <?php echo $blockAlias ?>CountryIsRequired($('<?php echo $editBlock->getCountryId() ?>'));
        });
    });

    //]]>
</script>
